
# Start the FastAPI server in a new window
Start-Process powershell -ArgumentList "uvicorn main:app --reload"

# Wait a few seconds for the server to start
Start-Sleep -Seconds 5

Write-Host "`nTesting /api/health ..."
Invoke-RestMethod -Uri "http://127.0.0.1:8000/api/health" -Method GET | ConvertTo-Json

Write-Host "`nTesting /api/test ..."
Invoke-RestMethod -Uri "http://127.0.0.1:8000/api/test" -Method GET | ConvertTo-Json

Write-Host "`nTesting /api/detect_ai ..."
$body = @{ text = "This is a test text generated by AI." } | ConvertTo-Json
Invoke-RestMethod -Uri "http://127.0.0.1:8000/api/detect_ai" -Method POST -Body $body -ContentType "application/json" | ConvertTo-Json

Write-Host "`nTesting /api/check_plagiarism ..."
$body2 = @{ doc = "This is a test document."; references = @("This is a reference text.") } | ConvertTo-Json
Invoke-RestMethod -Uri "http://127.0.0.1:8000/api/check_plagiarism" -Method POST -Body $body2 -ContentType "application/json" | ConvertTo-Json

Write-Host "`nTesting /api/stats ..."
Invoke-RestMethod -Uri "http://127.0.0.1:8000/api/stats" -Method GET | ConvertTo-Json

Write-Host "`nAll endpoint tests completed (if no errors appeared).
